apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-configmap

data:
  download-data.sh: |-
    {{- tpl (.Files.Get "config/download-data.sh") . | nindent 4 }}
  spark-load-reviews.sh: |-
    {{- tpl (.Files.Get "config/spark-load-reviews.sh") . | nindent 4 }}
  spark-load-metadata.sh: |-
    {{- tpl (.Files.Get "config/spark-load-metadata.sh") . | nindent 4 }}
  spark-deduplicate-data.sh: |-
    {{- tpl (.Files.Get "config/spark-deduplicate-data.sh") . | nindent 4 }}
  spark-top-categories-ratings.sh: |-
    {{- tpl (.Files.Get "config/sspark-top-categories-ratings.sh") . | nindent 4 }}
